# Generated by Django 4.0.3 on 2022-03-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Subjects',
            new_name='Course_Subject',
        ),
    ]
