# Generated by Django 4.0.3 on 2022-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_course_subjects_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
