# Generated by Django 4.0.3 on 2022-04-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_class_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
