# Generated by Django 4.0.3 on 2022-04-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teacher_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='no image', upload_to=''),
        ),
    ]
