# Generated by Django 4.0.3 on 2022-04-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_schedule',
            old_name='End_Time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='class_schedule',
            old_name='Start_Time',
            new_name='start_time',
        ),
    ]
