# Generated by Django 4.0.3 on 2022-04-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_end_time_class_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student Schedule',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Student Subject',
            },
        ),
    ]
