# Generated by Django 4.0.3 on 2022-04-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_studentschedule_studentsubject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubject',
            old_name='student_id',
            new_name='id',
        ),
    ]
