# Generated by Django 4.0.3 on 2022-04-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_student_id_studentsubject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='full_name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
