# Generated by Django 4.0.3 on 2022-04-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
