# Generated by Django 4.0.3 on 2022-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('profile_image', models.ImageField(default='no image', upload_to='api/students/images/')),
            ],
        ),
    ]
