# Generated by Django 4.0.3 on 2022-04-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
    ]
