# Generated by Django 4.0.3 on 2022-04-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_studentprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='user_id',
            new_name='user_id_id',
        ),
    ]
