# Generated by Django 4.0.3 on 2022-04-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_teacherprofile_alter_student_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSubject',
            new_name='UserSubject',
        ),
        migrations.AlterModelOptions(
            name='usersubject',
            options={'verbose_name_plural': 'User Subject'},
        ),
    ]
