# Generated by Django 4.0.3 on 2022-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_studentsubject_usersubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
