# Generated by Django 4.0.3 on 2022-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usersubject_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'User Schedule',
            },
        ),
        migrations.DeleteModel(
            name='StudentSchedule',
        ),
    ]
