# Generated by Django 4.0.3 on 2022-04-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userschedule_delete_studentschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='no image', upload_to='api/teachers/images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userschedule',
            options={},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.DateField()),
                ('att_status', models.CharField(max_length=30)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
            ],
        ),
    ]
