# Generated by Django 4.0.3 on 2022-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_attendancelist_alter_userschedule_options_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
