# Generated by Django 4.0.3 on 2022-04-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_attendancelist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelist',
            old_name='teacher_user_id',
            new_name='user_id',
        ),
    ]
