# Generated by Django 4.0.3 on 2022-04-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_teacher_user_id_attendancelist_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
