# Generated by Django 4.0.3 on 2022-04-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_user_id_attendancelist_teacher_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubject',
            name='course_name',
        ),
    ]
