# Generated by Django 4.0.3 on 2022-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_attendancelist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelist',
            name='class_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
