# Generated by Django 4.0.3 on 2022-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_stdlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelist',
            name='profile_image',
            field=models.ImageField(default='no image', upload_to='api/students/images/'),
        ),
        migrations.DeleteModel(
            name='StdList',
        ),
    ]
