# Generated by Django 4.0.3 on 2022-04-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_attendancelist_profile_image_delete_stdlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.FileField(default='no image', upload_to='api/teachers/images/'),
        ),
    ]
