# Generated by Django 4.0.3 on 2022-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_teacherprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(default='no image', upload_to='api/teachers/images/'),
        ),
    ]
