# Generated by Django 4.0.3 on 2022-04-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_imagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_schedule',
            name='class_venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='class_venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
