# Generated by Django 4.0.3 on 2022-04-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_class_schedule_class_venue_userschedule_class_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_schedule',
            old_name='class_Id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='class_schedule',
            old_name='subject_Id',
            new_name='subject_id',
        ),
    ]
