# Generated by Django 4.0.3 on 2022-04-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_rename_class_id_class_schedule_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_subject',
            old_name='course_Id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course_subject',
            old_name='subject_Id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='student_course',
            old_name='course_Id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='student_course',
            old_name='student_Id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='student_schedule',
            old_name='class_schedule_Id',
            new_name='class_schedule_id',
        ),
        migrations.RenameField(
            model_name='student_schedule',
            old_name='student_Id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='teacher_course',
            old_name='course_Id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='teacher_course',
            old_name='teacher_Id',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='teacher_schedule',
            old_name='class_schedule_Id',
            new_name='class_schedule_id',
        ),
        migrations.RenameField(
            model_name='teacher_schedule',
            old_name='teacher_Id',
            new_name='teacher_id',
        ),
    ]
