# Generated by Django 4.0.3 on 2022-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_rename_course_id_course_subject_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.FileField(default='no image', upload_to='api/students/images/'),
        ),
    ]
