# Generated by Django 4.0.3 on 2022-04-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubject',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='user_id',
        ),
    ]
