# Generated by Django 4.0.3 on 2022-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_usersubject_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='full_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='usersubject',
            name='subject_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersubject',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
