# Generated by Django 4.0.3 on 2022-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_usersubject_full_name_usersubject_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='api/students/images/user2.png', upload_to='api/students/images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(default='api/teachers/images/user2.png', upload_to='api/teachers/images/'),
        ),
    ]
