# Generated by Django 4.0.3 on 2022-04-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_student_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageList',
        ),
    ]
