# Generated by Django 4.0.3 on 2022-04-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_delete_imagelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(default='', max_length=10)),
                ('att_date', models.DateField()),
                ('att_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(default='', max_length=10)),
                ('att_date', models.DateField()),
                ('att_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('present', models.CharField(max_length=10)),
                ('absent', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_status', models.CharField(max_length=10)),
                ('ssid', models.CharField(max_length=100)),
                ('class_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.class_schedule')),
            ],
        ),
    ]
