# Generated by Django 4.0.3 on 2022-04-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_attendancelistrecord_attendancerecord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceList',
        ),
        migrations.DeleteModel(
            name='AttendanceListRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.RemoveField(
            model_name='session',
            name='class_schedule_id',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='StudentSubjectAttendance',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.DeleteModel(
            name='UserSchedule',
        ),
        migrations.DeleteModel(
            name='UserSubject',
        ),
        migrations.AddField(
            model_name='class_schedule',
            name='session_status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='class_schedule',
            name='ssid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
