# Generated by Django 4.0.3 on 2022-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_delete_attendancelist_delete_attendancelistrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_user_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(default='', max_length=10)),
                ('profile_image', models.ImageField(default='no image', upload_to='api/students/images/')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(default='', max_length=10)),
                ('att_date', models.DateField()),
                ('att_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(default='', max_length=10)),
                ('att_date', models.DateField()),
                ('att_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('profile_image', models.ImageField(default='no image', upload_to='api/students/images/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('present', models.CharField(max_length=10)),
                ('absent', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('profile_image', models.ImageField(default='no image', upload_to='api/teachers/images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('class_venue', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('full_name', models.CharField(default='Null', max_length=200)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'User Subject',
            },
        ),
    ]
