# Generated by Django 4.0.3 on 2022-04-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_attendancelist_attendancelistrecord_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelist',
            name='class_id',
            field=models.IntegerField(default=0),
        ),
    ]
